# Generated by Django 4.2.27 on 2025-12-12 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
        migrations.AddField(
            model_name='sale',
            name='channel',
            field=models.CharField(choices=[('POS', 'In-Store'), ('WEB', 'Online Store')], default='POS', max_length=10),
        ),
        migrations.AddField(
            model_name='sale',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending (Online)'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='COMPLETED', max_length=20),
        ),
        migrations.AlterField(
            model_name='product',
            name='reorder_level',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='stocktransaction',
            name='reference',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
